// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 Ray Klundt
// mathBasher is also available under a commercial license — see COMMERCIAL.md

/**
 * Stable string keys for every preloadable sprite asset. Mirrors the
 * `audioKeys.ts` pattern: every reference to a sprite asset goes through
 * a constant here so a typo doesn't silently fall through to a runtime
 * "key not found" warning.
 *
 * Per [ADR-0010](../../docs/adrs/ADR-0010-sprite-tier-strategy.md), sprite
 * art ships in two tiers (128px and 192px). The loader picks ONE tier at
 * boot from viewport × DPR and uses that tier's URL prefix for all asset
 * loads. Same filename across tiers means a single asset key works
 * regardless of which tier was loaded — only the URL prefix changes.
 *
 * Frame layout: each WebP is a horizontal-row spritesheet of
 * `FRAMES_PER_SPRITE` frames at `<tier>×<tier>` px each, extracted at
 * `SPRITE_FPS` from a 24 fps source (24÷12 = clean integer downsample).
 */

/**
 * Canonical / expected frame count per spritesheet, assuming the source
 * video is the standard 5.21s at 24 fps and the extractor runs at 12 fps.
 *
 * **DO NOT trust this for animation registration.** The pipeline can
 * produce variable frame counts in practice — ffmpeg's frame-rate
 * filter dedups repeated source frames, so a source with VFR encoding
 * or a slight duration mismatch produces fewer than 63 actual frames.
 * Phaser's `generateFrameNumbers(key, { start: 0 })` (omit `end`)
 * uses the spritesheet's actual frame count at runtime — always
 * prefer that over hardcoding this constant.
 *
 * This constant is kept as documentation for the *target* source-video
 * shape ("aim for ~5.21s at 12 fps when generating new alien videos")
 * and for the CSS preview's default duration calculation. Sprint 0.6.3
 * Story 6 captures the rationale for not trusting it elsewhere.
 */
export const FRAMES_PER_SPRITE = 63;

/** Animation playback rate (frames per second). Matches extract --fps. */
export const SPRITE_FPS = 12;

/**
 * Source-video batches that have been processed through the sprite
 * pipeline and have spritesheets on disk in `public/assets/sprites/aliens/`.
 *
 * Each entry's `rows × cols` defines the grid of that batch's source
 * video — `alien<N>-r<R>c<C>.webp` exists for every (R, C) in 0..rows-1
 * × 0..cols-1. `ALIEN_SPRITE_KEYS` below is derived from this list.
 *
 * Adding a new batch after a `pnpm sprite:extract` run: append a line
 * here. Removing a batch: delete the line + the sprite files. The
 * BootScene preload and the random-picker both read from
 * `ALIEN_SPRITE_KEYS`, so this is the single source of truth — no second
 * change needed.
 *
 * Tuning history:
 *   0.6.3 initial: hardcoded 5 batches × 3×3 = 45 keys based on the
 *     planned full alien-video-1..5 set.
 *   0.6.3 mid-sprint (option-C dark-bg pivot): existing batches were
 *     re-extracted from new dark-bg source videos. Only 3 of the 5
 *     videos had been re-generated by the user when game-side testing
 *     resumed; alien-video-4 + alien-video-5 are pending. The hardcoded
 *     45 caused BootScene to 404 on 15 nonexistent assets and the
 *     picker could choose missing-sprite keys. Switching to this
 *     data-driven BATCHES array fixed both.
 */
interface AlienSpriteBatch {
  readonly prefix: string;
  readonly rows: number;
  readonly cols: number;
}

export const ALIEN_SPRITE_BATCHES: readonly AlienSpriteBatch[] = [
  { prefix: 'alien1', rows: 3, cols: 3 },
  { prefix: 'alien2', rows: 3, cols: 3 },
  { prefix: 'alien3', rows: 3, cols: 4 },
  // alien4, alien5 pending re-generation at new option-C dark-bg defaults.
];

/**
 * Flat array of every alien sprite key currently shipped, derived from
 * `ALIEN_SPRITE_BATCHES`. Sprint 0.7's curation pass is expected to pick
 * a smaller subset for the production keepers — for sprint 0.6.3 the
 * full pool loads so we can validate sprite-on-block animation against
 * varied art.
 */
export const ALIEN_SPRITE_KEYS: readonly string[] = (() => {
  const keys: string[] = [];
  for (const batch of ALIEN_SPRITE_BATCHES) {
    for (let r = 0; r < batch.rows; r++) {
      for (let c = 0; c < batch.cols; c++) {
        keys.push(`${batch.prefix}-r${r}c${c}`);
      }
    }
  }
  return keys;
})();

export type SpriteTier = 128 | 192;

/**
 * Pick the sprite tier to load at boot.
 *
 * Heuristic: combined "device-pixels-wide" (viewport CSS width × DPR)
 *   ≥ 1920 → load the 192 tier (crisp on retina + desktop).
 *   < 1920 → load the 128 tier (saves ~2× bandwidth on phones; the GPU
 *     downscales 128→smaller invisibly, per ADR-0010 D3).
 *
 * Examples:
 *   iPhone 14    (390×844 @ DPR 3 = 1170)   → 128
 *   iPad Air     (1024×768 @ DPR 2 = 2048)  → 192
 *   1080p desktop (1920×1080 @ DPR 1)        → 192
 *   1366 laptop  (1366×768 @ DPR 1)          → 128
 *   Retina 14"   (1440×900 @ DPR 2 = 2880)   → 192
 *
 * Called once at boot from `BootScene.preload()` — no mid-session tier
 * swap (per ADR-0010 D4 + "out of scope" note).
 */
export function pickSpriteTier(viewportWidth: number, dpr: number): SpriteTier {
  return viewportWidth * dpr >= 1920 ? 192 : 128;
}

/** Asset URL for a given alien sprite key + tier. */
export function alienSpritePath(key: string, tier: SpriteTier): string {
  return `/assets/sprites/aliens/${tier}/${key}.webp`;
}

/**
 * Phaser animation key for the looping idle of a given sprite key.
 * Suffixed `-idle` so future per-sprite states (e.g. `-explode`,
 * `-hit`) compose without colliding with the asset key itself.
 */
export function alienAnimKey(key: string): string {
  return `${key}-idle`;
}

/**
 * Pick a random alien sprite key from `ALIEN_SPRITE_KEYS`. Uniform random
 * — no weighting, no per-batch quotas. Caller chooses when to seed the
 * RNG (sprint 0.6.3 just uses `Math.random`; future tournament/replay
 * modes might pass a seeded picker).
 */
export function pickRandomAlienSpriteKey(): string {
  const i = Math.floor(Math.random() * ALIEN_SPRITE_KEYS.length);
  return ALIEN_SPRITE_KEYS[i];
}
